spring:
  profile:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/threadasync
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update
hello:
  world: Hi World from local lets grow together
server:
  port: '9191'
